name: "Nightly Docker Image Build"

on:
  push:
    branches: ["*.*.x"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-assets:
    if: github.ref_name == github.event.repository.default_branch
    # See build-assets.yml for a list of the permissions and why they are needed
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: ./.github/workflows/build-assets.yml

  build-and-push-docker-image:
    if: github.ref_name == github.event.repository.default_branch
    needs: build-assets
    # See build-and-push-docker-image.yml for a list of the permissions and why they are needed
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    uses: ./.github/workflows/build-and-push-docker-image.yml
    with:
      tags: |
        type=raw,value=nightly-bin
